-- MySQL Script generated by MySQL Workbench
-- 04/10/16 10:40:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minicloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `key` TEXT NULL DEFAULT NULL,
  `key_encryption` VARCHAR(255) NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paths` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `parent_id` INT(11) UNSIGNED NULL,
  `path` VARCHAR(256) NOT NULL,
  `mktime` INT(11) NOT NULL,
  `mdtime` INT(11) NOT NULL,
  `checksum` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paths_user_idx` (`user_id` ASC),
  INDEX `fk_paths_parent_idx` (`parent_id` ASC),
  CONSTRAINT `fk_paths_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_paths_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `paths` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `files` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NULL,
  `path_id` INT(11) UNSIGNED NULL,
  `filename` VARCHAR(256) NOT NULL,
  `size` INT(11) NOT NULL,
  `mktime` INT(11) NOT NULL,
  `mdtime` INT(11) NOT NULL,
  `encryption` VARCHAR(256) NULL,
  `checksum` VARCHAR(64) NULL,
  `public` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_files_path_idx` (`path_id` ASC),
  INDEX `fk_files_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_files_path`
    FOREIGN KEY (`path_id`)
    REFERENCES `paths` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_files_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `versions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_id` INT UNSIGNED NOT NULL,
  `created` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_versions_file_idx` (`file_id` ASC),
  CONSTRAINT `fk_versions_file`
    FOREIGN KEY (`file_id`)
    REFERENCES `files` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
